### ISSUE TITLE
Definitions for Custom Functions implementation

### ISSUE THREAD

**Issue by mattarau** [dcflw/codemirror-lang-dentaku#8]
Hi! We are about to suggest an implementation for custom functions, as we need them in out use case, but I'd like to share some thoughts first, to see if they will match your expectations, so that we avoid a lot of rework on the PR.

The initial idea would be to adapt the current built-in functions implementation to be reused by the custom functions in order to have a single error handler logic on top of a merged list of built-in and custom functions.

To accomplish this, we would replace the current `builtInFunctions` Array with a Map that provides the functions name and its config:
```typescript
type DentakuFunctionConfig = {
  minArgs?: number;
  maxArgs?: number;
};

const builtInFunctions: Map<string, DentakuFunctionConfig>;
```

> This would make the `knownArgumentCounts` not necessary anymore.

Then, the `DentakuLinterOptions` would have the custom functions property added:
```typescript
export interface DentakuLinterOptions {
  /** List of variable names to not treat as undefined. */
  knownVariables?: Array<string>;
  /** Map of custom function and their configuration. */
  customFunctions?: Map<string, DentakuFunctionConfig>;
  /** Custom error messages. */
  messages?: ErrorMessages;
}
```

These `customFunctions` then get merged with the built-in ones in the linter function:
```typescript
export function dentakuLinter({
  knownVariables = [],
  messages = defaultErrorMessages,
  customFunctions = new Map(),
}: DentakuLinterOptions = {}): LintSource {
  return (view) => {
    const diagnostics: Diagnostic[] = [];

    // We set the builtInFunctions last, to avoid override from customFunctions 
    const knownFunctions = new Map([...customFunctions, ...builtInFunctions]);
   
   // ....

   // replace builtInFunctions.includes(variableName) with knownFunctions.has(variableName)

   // .... more details below
}
```

The error messages would have both `expectedAtLeastOneParameter` and `parameterCountMismatch` replaced by:
```typescript
export interface ErrorMessages {
  expectedExactArgumentCount: (
    count: number,
  ) => string;
  expectedMinimumArgumentCount: (
    count: number,
  ) => string;
  expectedArgumentCountRange: (
    actualCount: number,
    minCount: number,
    maxCount: number,
  ) => string;
}
```

And the `ArgList` linting implementation would be changed to:
```typescript
case "ArgList": {
  const argumentCount = nodeRef.node.getChildren("Expression").length;
  const functionNameNode = nodeRef.node.parent?.firstChild;
  if (!functionNameNode) {
    return;
  }
  const functionName = view.state.sliceDoc(
    functionNameNode.from,
    functionNameNode.to
  );

  // Getting the config directly from the merged Map
  const { minArgs, maxArgs } = knownFunctions.get(functionName) ?? {};
  
  // If there's no minimum arguments there's no need to lint args
  if (!Number.isInteger(minArgs)) {
    return;
  }

  if (
    !Number.isInteger(maxArgs) &&
    minArgs > argumentCount
  ) {
    diagnostics.push({
      from: nodeRef.from,
      to: nodeRef.to,
      severity: "error",
      message: messages.expectedMinimumArgumentCount(
        minArgs
      ),
    });
  } else if (
    Number.isInteger(maxArgs) &&
    minArgs === maxArgs &&
    minArgs !== argumentCount
  ) {
    diagnostics.push({
      from: nodeRef.from,
      to: nodeRef.to,
      severity: "error",
      message: messages.expectedExactArgumentCount(
        minArgs
      ),
    });
  } else if (
    Number.isInteger(maxArgs) &&
    minArgs < maxArgs &&
    (minArgs > argumentCount ||
    maxArgs < argumentCount)
  ) {
    diagnostics.push({
      from: nodeRef.from,
      to: nodeRef.to,
      severity: "error",
      message: messages.expectedArgumentCountRange(
        argumentCount,
        minArgs, 
        maxArgs
      ),
    });
  }
  break;
}
```

All of this, off course, would require that we also add the min and max arguments values of all built-in functions with no fixed arity. 

It should also allow us to provide a single input of custom functions that are then passed down to the linter and autocomplete without requiring independent configs for them.

It may need to be adapted to fit missed scenarios, but in any case, let me know if we missed something and hopefully we could send a PR for these features soon.

Cheers!

**Comment by illright** [comment]
Hi! Solid proposal overall, I have only a few comments:
1. I would prefer the function config to have both fields required, with `min` being set to `0` and `max` to `Infinity` if there is no limit on either side. That way we can't represent invalid states, such as functions without both fields
2. Not sure I understand why the arguments don't need to be linted if there is no minimum. There could still be a maximum
3. I'd like custom functions to also be auto-completable, so we should think about the ergonomics of defining a list of custom functions in one place and then being able to pass that to both the linter and the autocomplete (maybe with a simple transformation)

Apart from that, I have no objections, and a PR would be greatly appreciated!

**Comment by mattarau** [comment]
Hi! Thanks for the quick reply. Addressing your points:

1. and 2. The reason for the incomplete suggestion is probably due to our use case, where all functions that have a `max` have a also `min`, otherwise it is a function without expected args. My bad. In any case, I'll take the suggestion of the `0` and `Infinity` defaults for the soon-to-come PR.
3. That's exactly what I meant with a single input passed down to the linter and autocomplete. Something like this:

```typescript
export function dentaku({
  linterOptions: { codeMirrorConfig, ...linterOptions } = {},
  completionOptions,
  customFunctions = new Map(),
}: {
  linterOptions?: {
    codeMirrorConfig?: Parameters<typeof linter>[1];
  } & DentakuLinterOptions;
  completionOptions?: DentakuLanguageCompletionOptions;
  customFunctions?: Map<string, DentakuFunctionConfig>;
} = {}) {
  return new LanguageSupport(dentakuLanguage, [
    dentakuLanguage.data.of({
      autocomplete: dentakuCompletions({
        ...completionOptions,
        customFunctionsEntries: [...customFunctions.keys()].map((name) => ({
          label: name,
          type: "function",
        })),
      }),
    }),
    linter(
      dentakuLinter({ ...linterOptions, customFunctions }),
      codeMirrorConfig
    ),
  ]);
}
```

But the exact implementation may depend on other factors.

So, let's get it started then. Expect a PR soon.

Cheers!
